Email-Marketing-System/EMS.Web/Areas/User/Controllers/SmtpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Autofac;
using EMS.Framework;
using EMS.Web.Areas.User.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace EMS.Web.Areas.User.Controllers
{

    [Area("User")]
    public class SmtpController : Controller
    {
        private readonly IConfiguration _configuration;
        public SmtpController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            var model = Startup.AutofacContainer.Resolve<SmtpModel>();
            return View(model);
        }

        public IActionResult CreateSmtp()
        {
            var model = new CreateSmtpModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateSmtp(
          [Bind(nameof(CreateSmtpModel.SmtpProvider),
            nameof(CreateSmtpModel.SmtpHostServer),
            nameof(CreateSmtpModel.Port),
            nameof(CreateSmtpModel.Port),
            nameof(CreateSmtpModel.EnableSsl),
            nameof(CreateSmtpModel.UserName),
            nameof(CreateSmtpModel.Password))] CreateSmtpModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    model.Create();
                    model.Response = new ResponseModel("Smtp configuration creation successful.", ResponseType.Success);
                    return RedirectToAction("Index");
                }
                catch (DuplicationException ex)
                {
                    model.Response = new ResponseModel(ex.Message, ResponseType.Failure);
                    // error logger code
                }
                catch (Exception ex)
                {
                    model.Response = new ResponseModel("Smtp configuration creation failued.", ResponseType.Failure);
                    // error logger code
                }
            }
            return View(model);
        }
        public IActionResult EditSmtp(int id)
        {
            var model = new EditSmtpModel();
            model.Load(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditSmtp(
        [Bind(
            nameof(EditSmtpModel.Id)
            ,nameof(EditSmtpModel.SmtpProvider),
            nameof(EditSmtpModel.SmtpHostServer),
            nameof(EditSmtpModel.Port),
            nameof(EditSmtpModel.EnableSsl),
            nameof(EditSmtpModel.UserName),
            nameof(EditSmtpModel.Password))] EditSmtpModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    model.Edit();
                    model.Response = new ResponseModel("Smtp configuration editing successful.", ResponseType.Success);
                    return RedirectToAction("Index");
                }
                catch (DuplicationException ex)
                {
                    model.Response = new ResponseModel(ex.Message, ResponseType.Failure);
                    // error logger code
                }
                catch (Exception ex)
                {
                    model.Response = new ResponseModel("Smtp configuration creation failued.", ResponseType.Failure);
                    // error logger code
                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteSmtp(int id)
        {
            if (ModelState.IsValid)
            {
                var model = new SmtpModel();
                try
                {
                    var provider = model.Delete(id);
                    model.Response = new ResponseModel($"Smtp {provider} successfully deleted.", ResponseType.Success);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    model.Response = new ResponseModel("Smtp delete failued.", ResponseType.Failure);
                    // error logger code
                }
            }
            return RedirectToAction("index");
        }

        public IActionResult GetSmtps()
        {
            var tableModel = new DataTablesAjaxRequestModel(Request);
            var model = Startup.AutofacContainer.Resolve<SmtpModel>();
            var data = model.GetSmtps(tableModel);
            return Json(data);
        }

    }

}

Email-Marketing-System/EMS.Web/Areas/User/Views/Smtp/CreateSmtp.cshtml
@model EMS.Web.Areas.User.Models.CreateSmtpModel

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>New Smtp Configuration</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">New Configuration</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Add a new Smtp Configuration</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <partial name="_ActionMessage" model="@Model.Response" />
                        <form asp-area="User" asp-controller="Smtp" asp-action="CreateSmtp" method="post" class="form-horizontal">
                            <div asp-validation-summary="All" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="SmtpProvider" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="SmtpProvider" class="form-control" />
                                    <span asp-validation-for="SmtpProvider" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="SmtpHostServer" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="SmtpHostServer" class="form-control" />
                                    <span asp-validation-for="SmtpHostServer" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="Port" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="Port" class="form-control" />
                                    <span asp-validation-for="Port" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="EnableSsl" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="EnableSsl" class="form-check"/>
                                    <span asp-validation-for="EnableSsl" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="UserName" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="UserName" class="form-control" />
                                    <span asp-validation-for="UserName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="Password" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="Password" class="form-control" type="password"/>
                                    <span asp-validation-for="Password" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" class="btn btn-default" value="Submit" />
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

@section PageScripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
}

Email-Marketing-System/EMS.Web/Areas/User/Views/Smtp/EditSmtp.cshtml
@model EMS.Web.Areas.User.Models.EditSmtpModel

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit Book</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Edit Book</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Edit Smtp Configuration</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <partial name="_ActionMessage" model="@Model.Response" />
                        <form asp-area="User" asp-controller="Smtp" asp-action="EditSmtp" method="post" class="form-horizontal">
                            <div asp-validation-summary="All" class="text-danger"></div>
                            <input type="hidden" asp-for="Id" />
                            <div class="form-group">
                                <label asp-for="SmtpProvider" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="SmtpProvider" class="form-control" />
                                    <span asp-validation-for="SmtpProvider" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="SmtpHostServer" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="SmtpHostServer" class="form-control" />
                                    <span asp-validation-for="SmtpHostServer" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="Port" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="Port" class="form-control" />
                                    <span asp-validation-for="Port" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="EnableSsl" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="EnableSsl" class="form-check" />
                                    <span asp-validation-for="EnableSsl" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="UserName" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="UserName" class="form-control" />
                                    <span asp-validation-for="UserName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="Password" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="Password" class="form-control" type="password" />
                                    <span asp-validation-for="Password" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" class="btn btn-default" value="Submit" />
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

@section PageScripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
}

Email-Marketing-System/EMS.Web/Areas/User/Views/Smtp/Index.cshtml
@model EMS.Web.Areas.User.Models.SmtpModel

@section PageStyles
{
    <!-- DataTables -->
    <link rel="stylesheet" href="/admin/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>DataTables</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">DataTables</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">DataTable with default features</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <partial name="_ActionMessage" model="@Model.Response" />
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Smtp Provider</th>
                                    <th>Host Server</th>
                                    <th>Port</th>
                                    <th>UserName</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>Smtp Provider</th>
                                    <th>Host Server</th>
                                    <th>Port</th>
                                    <th>UserName</th>
                                    <th>Action</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

<div class="modal fade" id="modal-default">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Delete</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure, you want to delete?</p>
                <form id="deleteForm" action="/user/smtp/deletesmtp" method="post">
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="deleteId" value="" name="id" />
                </form>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" id="deleteButton" class="btn btn-danger">Yes, Delete!</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

@section PageScripts
{
    <!-- DataTables -->
    <script src="/admin/plugins/datatables/jquery.dataTables.js"></script>
    <script src="/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <!-- page script -->
    <script>
        $(function () {
            $('#example1').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "/User/Smtp/GetSmtps",
                "columnDefs": [
                    {
                        "orderable": false,
                        "targets": 4,
                        "render": function (data, type, row) {
                            return `<button type="submit" class="btn btn-info btn-sm" onclick="window.location.href='/user/smtp/editsmtp/${data}'" value='${data}'>
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Edit
                                    </button>
                                    <button type="submit" class="btn btn-danger btn-sm show-bs-modal" href="#" data-id='${data}' value='${data}'>
                                        <i class="fas fa-trash">
                                        </i>
                                        Delete
                                    </button>`;
                        }
                    }
                ]
            });

            $('#example1').on('click', '.show-bs-modal', function (event) {
                var id = $(this).data("id");
                var modal = $("#modal-default");
                modal.find('.modal-body p').text('Are you sure you want to delete this record?')
                //$("#deleteForm").attr("action", "/admin/category/delete/" + id );
                $("#deleteId").val(id);
                modal.modal('show');
            });

            $("#deleteButton").click(function () {
                $("#deleteForm").submit();
            });
        });
    </script>
}